// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateUserByID.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET email = $2,
    hashed_password = $3,
    updated_at = Now()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserByIDParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateUserByIDRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (UpdateUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserByID, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
